#!/bin/bash

grub() {
    sudo cp -f grub /etc/default/grub
    sudo update-grub
}

tmux() {
    mkdir ~/.config/tmux
    cp -f tmux.conf ~/.config/tmux/tmux.conf
}

workspaces() {
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5  "['<Alt>5']"
}

if [ -z $1 ]
then
    grub
    tmux
    workspaces
    exit
fi

for config in "$@"
do
    case $config in
	"grub")
	    grub
	    ;;
	"tmux")
	    tmux
	    ;;
	"workspaces")
	    workspaces
	    ;;
    esac
done
