#!/bin/bash

grub() {
    printf "${CYAN}configuring grub${NC}\n"
    sudo cp -f grub /etc/default/grub
    sudo update-grub
    printf "${GREEN}done${NC}\n"
}

tmux() {
    printf "${CYAN}configuring tmux${NC}\n"
    mkdir ~/.config/tmux
    cp -f tmux.conf ~/.config/tmux/tmux.conf
    printf "${GREEN}done${NC}\n"
}

workspaces() {
    printf "${CYAN}configuring workspaces${NC}\n"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-$2  "['<Alt>5']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-$2  "['<Alt><Shift>5']"
    printf "${GREEN}done${NC}\n"
}

alacritty() {
    printf "${CYAN}configuring alacritty${NC}\n"
    mkdir ~/.config/alacritty
    cp -f alacritty.yml ~/.config/alacritty/alacritty.yml
    printf "${GREEN}done${NC}\n"
}

RED='\033[0;31m'
NC='\033[0m' 
CYAN='\033[0;36m'
GREEN='\033[0;32m'

if [ -z $1 ]
then
    grub
    tmux
    workspaces
	alacritty
    exit
fi

for config in "$1"
do
    case $config in
	grub)
	    grub
	    ;;
	tmux)
	    tmux
	    ;;
	workspaces)
	    workspaces
	    ;;
	alacritty)
	    workspaces
	    ;;
	*)
	    printf "${RED}wrong config parameter${NC}\n"
	    ;;
    esac
done
